packages:
- 'simple-notebooks/web-app'
- 'simple-notebooks/node-engine'
- 'simple-notebooks/p5'
- 'simple-notebooks/packages/*'
- 'lezer-playground'
- 'lezer-playground/packages/*'
- 'packages/*'
- 'paintbrush/extension'
- 'paintbrush/paintbrush-in-page-editor'
- 'codemirror-editor-in-chief'
